### ISSUE TITLE
Install failing

### ISSUE THREAD

**Issue by aatrostle** [atom/autocomplete-emojis#8]
I've tried installing this package via the UI and `apm`, both fail. I'm not wholly familiar with the ecosystem or I might debug more...

```
➜   atom -v
Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

```
➜   apm install atom/autocomplete-emojis
Cloning https://github.com/atom/autocomplete-emojis.git ✓
Installing modules ✗
npm ERR! Darwin 15.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/aarontrostle/.atom/.apm/.apmrc" "--userconfig" "/Users/aarontrostle/.atom/.apmrc" "install" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3

npm ERR! version not found: grunt-apm@0.0.1
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/z6/24hfpgdx3nlcs__r3tffhx0c0000gn/T/atom-git-package-clone-116416-9731-1yy8nyb/npm-debug.log
```

**Comment by eqot** [comment]
I could not reproduce the issue via the UI on Mac.

Via `apm`, could you try the following which does not include `atom/`.

```
$ apm install autocomplete-emojis
```

It works as expected.

```
$ atom -v
Atom    : 1.8.0-beta3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

**Comment by aatrostle** [comment]
As per your suggestion

```
➜  apm install autocomplete-emojis
Installing autocomplete-emojis to /Users/aarontrostle/.atom/packages ✗
undefined
```

You're using `1.8.0-beta3` version of Atom. I just installed that version and tried installing via the UI and the install still failed.

**Comment by eqot** [comment]
Hmmm, weird...
I have merged your commit and published the latest package to [here](https://atom.io/packages/autocomplete-emojis).
I do not think that `devDependencies` fixes the issue for users since **dev** means developers, but can you try `apm install atom/autocomplete-emojis` again or something like that?

**Comment by aatrostle** [comment]
Weird indeed, I agree, it's unclear why anything in `devDependencies` would cause an install issue since they are dependencies for **development**.

However the install is still failing for me 😞 

From the UI

![autocomplete-emojis-install-failure](https://cloud.githubusercontent.com/assets/643280/15450589/27c864f0-1f54-11e6-95c6-c203207a6a12.gif)

From normal `apm`

```
➜  apm install autocomplete-emojis
Installing autocomplete-emojis to /Users/aarontrostle/.atom/packages ✗
undefined
```

From `apm` using the git username/repo

```
➜  apm install atom/autocomplete-emojis
Cloning https://github.com/atom/autocomplete-emojis.git ✓
Installing modules ✗
npm WARN peerDependencies The peer dependency grunt@~0.4.1 included from grunt-coffee-jshint will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency coffee-script@>= 1.6 < 2 included from coffee-jshint will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 15.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/aarontrostle/.atom/.apm/.apmrc" "--userconfig" "/Users/aarontrostle/.atom/.apmrc" "install" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package grunt@1.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer load-grunt-tasks@3.5.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-coffee-jshint@0.3.0 wants grunt@~0.4.1

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/z6/24hfpgdx3nlcs__r3tffhx0c0000gn/T/atom-git-package-clone-116421-17985-5iosfi/npm-debug.log
```

Based on the last error I made the following change

``` diff
diff --git a/package.json b/package.json
index 81d094a..7660af3 100644
--- a/package.json
+++ b/package.json
@@ -16,7 +16,7 @@
     "fuzzaldrin": "^2.1.0"
   },
   "devDependencies": {
-    "grunt": "^1.0.1",
+    "grunt": "^0.4.5",
     "grunt-apm": "^1.0.1",
     "grunt-coffee-jshint": "^0.3.0",
     "grunt-contrib-watch": "^1.0.0",
```

and I was able to `apm install` from the repo directory without error

```
➜  pwd
/Users/aarontrostle/dev/autocomplete-emojis
➜  apm install
Installing modules ✓
```

**UPDATE** Been doing some more digging and my `node` comes from an `nvm` install via Homebrew. While I am not 100% sure, _this_ could somehow be the issue. I will try to test this in a day or so.

**Comment by eqot** [comment]
Thank you very much for the information.

I have updated package.json to remove grunt-coffee-jshint as a workaround. This should fix the issue on `apm install atom/autocomplete-emojis`.

But for the UI, I have no idea so far but `node` might cause the issue.

Just for your information, here are my configurations.
For `node`, I use `nvm` instead of Homebrew.

```
$ apm -v
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.7.4
```

```
$ nvm --version
0.31.0
```

```
$ node -v
v6.0.0
```

**Comment by aatrostle** [comment]
@eqot did you install `nvm` [the recommended way](https://github.com/creationix/nvm#installation) or via Homebrew? I'm hoping to find some time soon to test some things.

**Comment by eqot** [comment]
I installed `nvm` with the install script.

```
$ curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash
```

I will try to temporarily disable the current `nvm` with the install script and install it via Homebrew to check if I can reproduce this issue.

**Comment by aatrostle** [comment]
😅 Just noticed this is still open… I got a new computer and wasn't able to repro so I'm closing this.
